name: Android Kotlin

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/android.yml"
      - "build.gradle.kts"
      - "settings.gradle.kts"
      - "gradle.properties"
      - "gradle/wrapper/**"
      - "gradlew"
      - "gradlew.bat"
      - "config/detekt/**"
      - "tantivy-android/**"
  push:
    paths:
      - ".github/workflows/android.yml"
      - "build.gradle.kts"
      - "settings.gradle.kts"
      - "gradle.properties"
      - "gradle/wrapper/**"
      - "gradlew"
      - "gradlew.bat"
      - "config/detekt/**"
      - "tantivy-android/**"

concurrency:
  group: android-kotlin-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set Up Android SDK
        uses: android-actions/setup-android@v4

      - name: Install Android Packages
        run: |
          sdkmanager "platforms;android-36" "build-tools;36.0.0"

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Lint
        run: ./gradlew :tantivy-android:detekt

      - name: Android Lint
        run: ./gradlew :tantivy-android:lintRelease

      - name: API Docs
        run: ./gradlew :tantivy-android:dokkaGenerate

      - name: API Compatibility
        run: ./gradlew apiCheck

      - name: Test
        run: ./gradlew :tantivy-android:testDebugUnitTest
